# Generated by Django 3.1.7 on 2022-01-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image_path',
            field=models.CharField(default='', max_length=500),
        ),
    ]
